services:
  - type: web
    name: federated-learning-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main_server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.10
